name = "omikuji"
main = "./worker.js" # 新しいエントリポイントファイル
compatibility_date = "2025-03-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.next"

[build]
command = "npm run build"

[env.production]
vars = { ANTHROPIC_MODEL = "claude-3-haiku-20240307" }
