name = "omikuji"
main = "./.next/server/app/page.js"
compatibility_date = "2025-03-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.next/static"

[build]
command = "npm run build"

[env.production]
vars = { ANTHROPIC_MODEL = "claude-3-haiku-20240307" }
